- name: Deploy Namespaces
  vars:
    local_namespace: "{{ global_namespace }}-{{ environment_index }}"
  block:
    - name: Check if namespace is already deployed
      ansible.builtin.command: kubectl get namespace {{ local_namespace }} --ignore-not-found
      register: local_already_deployed_check
      retries: 2
      delay: 8
      ignore_errors: true
      changed_when: false

    - name: Create Namespace "{{ local_namespace }}"
      ansible.builtin.command: kubectl create namespace "{{ local_namespace }}"
      when: local_already_deployed_check.rc != 0
      changed_when: true
