environments: 15
namespace_name: "practice-namespace"
environment: "production"
replicas: 1
machines:
  - kali
  - ubuntu
  - ubuntu
kali_config:
  image: "kalilinux/kali-rolling"
  service_account: True
  service_account_name: "kali-service-account"
  container_commands:
    - while true; do sleep 30; done
  env:
    - name: "KALI_ENV_VAR"
      value: "some_value"
  ports:
    - container_port: 22
      target_port: 22
      port: 22
  role_rules:
    - api_groups: '[""]'
      resources: '["pods"]'
      verbs: '["get", "watch", "list"]'
  service_port: 8080
  service_type: "LoadBalancer"
ubuntu_config:
  image: "ubuntu:latest"
  service_account: True
  service_account_name: "ubuntu-service-account"
  container_commands:
    - while true; do sleep 30; done
  env:
    - name: "UBUNTU_ENV_VAR"
      value: "another_value"
  ports:
    - container_port: 80
      target_port: 80
      port: 80
  role_rules:
    - api_groups: '[""]'
      resources: '["pods"]'
      verbs: '["get", "watch", "list"]'
  service_port: 9090
  service_type: "LoadBalancer"
