############################################################################################
# Assumptions
# You have deployed a cluster (Can use the ansible script in my Nexus-2.0 repo)
# CNI, CSI are setup, CNI is capable of firewalling (calico default) Check Nexus-2.0 for deployment code
############################################################################################

# Required Dependencies, no error if already installed.
# - import_playbook: ../Metallb/basic.yml # Loadbalancer

- name: Create environments
  hosts: masters
  vars_files:
    - "./global-config.yml"
  become: true
  become_user: "{{ become_user_setting }}"
  tasks:
    - name: Deploy Namespaces
      ansible.builtin.include_tasks: ./machines/namespaces.yml
      loop: "{{ range(1, num_environments + 1) | list }}"
      loop_control:
        loop_var: env_index # Renaming to avoid conflict
      vars:
        environment_index: "{{ env_index }}" # Assign loop variable to environment_index

    - name: Deploy Kali Machines
      ansible.builtin.include_tasks: ./machines/kali.yml
      loop: "{{ range(1, num_environments + 1) | list }}"
      loop_control:
        loop_var: env_index # Renaming to avoid conflict
      vars:
        environment_index: "{{ env_index }}" # Assign loop variable to environment_index
      when: deploy_kali

    - name: Deploy Ubuntu Machines
      ansible.builtin.include_tasks: ./machines/ubuntu.yml
      loop: "{{ range(1, num_environments + 1) | list }}"
      loop_control:
        loop_var: env_index # Renaming to avoid conflict
      vars:
        environment_index: "{{ env_index }}" # Assign loop variable to environment_index
      when: deploy_ubuntu
